n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))
n4 = int(input('Digite o quarto número: '))
n5 = int(input('Digite o quinto número: '))
n6 = int(input('Digite o sexto número: '))
n7 = int(input('Digite o sétimo número: '))
n8 = int(input('Digite o oitavo número: '))
n9 = int(input('Digite o nono número: '))
n10 = int(input('Digite o décimo número: '))
n11 = int(input('Digite o décimo primeiro número: '))
n12 = int(input('Digite o décimo segundo número: '))
n13 = int(input('Digite o décimo terceiro número: '))
n14 = int(input('Digite o décimo quarto número: '))
n15 = int(input('Digite o décimo quinto número: '))

resultado = n1 * n2 * n3 * n4 * n5 * n6 * n7 * n8 * n9 * n10 * n11 * n12 * n13 * n14 * n15
print (f'Este é o resultado: {resultado}')